name: 'pr-comment'
description: 'It is a pr-comment action'
author: 'Mohamed Hani'

# Define your inputs here.
inputs:
  owner:
    description: 'Github Owner Name'
    required: true
  repo:
    description: 'GitHub Repository Name'
    required: true
  pr_number:
    description: 'Pull Request Number'
    required: true
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.js
